/* Autogenerated with kurento-module-creator */

#ifndef __HLSCONVERTOR_INTERNAL_HPP__
#define __HLSCONVERTOR_INTERNAL_HPP__

#include "HLSConvertor.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace hlsconvertor
{

class HLSConvertorConstructor
{
public:
  HLSConvertorConstructor () {}
  ~HLSConvertorConstructor () {}

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* hlsconvertor */
} /* module */
} /* kurento */

#endif /*  __HLSCONVERTOR_INTERNAL_HPP__ */
