/* Autogenerated with kurento-module-creator */

#ifndef __HLSCONVERTOR_HPP__
#define __HLSCONVERTOR_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"

namespace kurento
{
namespace module
{
namespace hlsconvertor
{
class HLSConvertor;
} /* hlsconvertor */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::hlsconvertor::HLSConvertor> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace hlsconvertor
{
class HLSConvertor : public virtual Filter
{

public:
  HLSConvertor () {};
  virtual ~HLSConvertor () {};

  virtual std::string getType () const {
    return "HLSConvertor";
  }

  virtual std::string getModule () const {
    return "hlsconvertor";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* hlsconvertor */
} /* module */
} /* kurento */

#endif /*  __HLSCONVERTOR_HPP__ */
