/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "HLSConvertorImpl.hpp"
#include "HLSConvertorImplFactory.hpp"
#include "HLSConvertorInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace hlsconvertor
{

MediaObjectImpl *HLSConvertorImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  HLSConvertorConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

        GST_DEBUG ("@rt createObjectPointer: A new pad %s was created\n", "name");
  return createObject (conf, constructor.getMediaPipeline() );
}

void
HLSConvertorImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
        GstPad * pad;
        gchar *name;
        pad = gst_element_get_request_pad (element, "sink");
        name = gst_pad_get_name (pad);
        GST_DEBUG ("@rt invoke: A new pad %s was created\n", name);
        g_free (name);
  FilterImpl::invoke (obj, methodName, params, response);
}

bool
HLSConvertorImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

        GstPad * pad;
        gchar *name;
        pad = gst_element_get_request_pad (element, "sink");
        name = gst_pad_get_name (pad);
        GST_DEBUG ("@rt connect: A new pad %s was created\n", name);
        g_free (name);
        return true;
  return FilterImpl::connect (eventType, handler);
}

void
HLSConvertorImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'HLSConvertorImpl' cannot be deserialized as an object");
  }
}
} /* hlsconvertor */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::hlsconvertor::HLSConvertorImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::hlsconvertor::HLSConvertorImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::hlsconvertor::HLSConvertorImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::hlsconvertor::HLSConvertor> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::hlsconvertor::HLSConvertorImpl> aux = std::dynamic_pointer_cast<kurento::module::hlsconvertor::HLSConvertorImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::hlsconvertor::HLSConvertor> (aux);
}

} /* kurento */
