/* Autogenerated with kurento-module-creator */

#include "HLSConvertorImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace hlsconvertor
{

void dummyHlsconvertor ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<HLSConvertor> object;

    s.SerializeNVP (object);
  }
}

} /* hlsconvertor */
} /* module */
} /* kurento */
