/* Autogenerated with kurento-module-creator */

#ifndef __HLSCONVERTOR_IMPL_HPP__
#define __HLSCONVERTOR_IMPL_HPP__

#include "FilterImpl.hpp"
#include "HLSConvertor.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace hlsconvertor
{
class HLSConvertorImpl;
} /* hlsconvertor */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::hlsconvertor::HLSConvertorImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace hlsconvertor
{

class HLSConvertorImpl : public FilterImpl, public virtual HLSConvertor
{

public:

  HLSConvertorImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~HLSConvertorImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* hlsconvertor */
} /* module */
} /* kurento */

#endif /*  __HLSCONVERTOR_IMPL_HPP__ */
