/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Filter = kurentoClient.register.abstracts.Filter;


/**
 * Create an element
 *
 * @classdesc
 *  HLSConvertor interface. Documentation about the module
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:hlsconvertor.HLSConvertor
 */
function HLSConvertor(){
  HLSConvertor.super_.call(this);
};
inherits(HLSConvertor, Filter);


/**
 * @alias module:hlsconvertor.HLSConvertor.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
HLSConvertor.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  }
};

/**
 * @alias module:hlsconvertor.HLSConvertor.events
 *
 * @extends module:core/abstracts.Filter.events
 */
HLSConvertor.events = Filter.events;


/**
 * Checker for {@link module:hlsconvertor.HLSConvertor}
 *
 * @memberof module:hlsconvertor
 *
 * @param {external:String} key
 * @param {module:hlsconvertor.HLSConvertor} value
 */
function checkHLSConvertor(key, value)
{
  if(!(value instanceof HLSConvertor))
    throw ChecktypeError(key, HLSConvertor, value);
};


module.exports = HLSConvertor;

HLSConvertor.check = checkHLSConvertor;
